-- MySQL Script generated by MySQL Workbench
-- Wed Sep 22 17:21:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Announcement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Announcement` (
  `announcementID` INT NOT NULL AUTO_INCREMENT,
  `announcementMessage` TEXT NOT NULL,
  PRIMARY KEY (`announcementID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Complaint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Complaint` (
  `complaintID` INT NOT NULL,
  `complaintMessage` TEXT NOT NULL,
  PRIMARY KEY (`complaintID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contract` (
  `ContractID` INT NOT NULL AUTO_INCREMENT,
  `EmployeeId` INT NOT NULL,
  `jobTitle` VARCHAR(45) NOT NULL,
  `floor` VARCHAR(45) NULL,
  `workingHours` INT NOT NULL,
  `salaryPerHour` INT NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `reasenForTermination` TEXT NOT NULL,
  PRIMARY KEY (`ContractID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DeletedEmployee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DeletedEmployee` (
  `employeeID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `phoneNumber` INT NULL,
  `email` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  `dateOfBirth` DATE NULL,
  `bsn` INT NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`employeeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `departmentID` INT NOT NULL AUTO_INCREMENT,
  `departmentName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`departmentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `employeeID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `phoneNumber` INT NULL,
  `email` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  `dateOfBirth` DATE NULL,
  `bsn` INT NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`employeeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Jobs` (
  `jobID` INT NOT NULL AUTO_INCREMENT,
  `jobTitle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`jobID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `productID` INT NOT NULL AUTO_INCREMENT,
  `barcode` VARCHAR(10) NOT NULL,
  `ProductName` VARCHAR(45) NOT NULL,
  `PorductType` VARCHAR(45) NOT NULL,
  `AmountInDepot` INT NOT NULL DEFAULT 0,
  `AmountInSales` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`productID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductTypes` (
  `ProductTypeID` INT NOT NULL AUTO_INCREMENT,
  `ProductTypesName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ProductTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Scheduel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Scheduel` (
  `empID` INT NOT NULL,
  `scheduelDay` VARCHAR(45) NOT NULL,
  `time` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shifts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shifts` (
  `day` VARCHAR(45) NOT NULL,
  `Morning` INT NOT NULL DEFAULT 1,
  `Afternoon` INT NOT NULL DEFAULT 1,
  `evening` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`day`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- add table `mydb`.`ShelfReplenishment`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `dbi461266`.`ShelfReplenishment` (
  `ShelfReplenishmentID` INT NOT NULL AUTO_INCREMENT,
  `ProductID` INT NOT NULL,
  `Amount` INT NOT NULL,
  PRIMARY KEY (`ShelfReplenishmentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- add table `mydb`.`Restock Requests`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `dbi461266`.`RestockReplenishment` (
  `RestockReplenishmentID` INT NOT NULL AUTO_INCREMENT,
  `ProductID` INT NOT NULL,
  `Amount` INT NOT NULL,
  PRIMARY KEY (`RestockReplenishmentID`))
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Announcement`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Announcement` (`announcementID`, `announcementMessage`) VALUES (1, 'hello');
INSERT INTO `mydb`.`Announcement` (`announcementID`, `announcementMessage`) VALUES (2, 'first');
INSERT INTO `mydb`.`Announcement` (`announcementID`, `announcementMessage`) VALUES (3, 'Error');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Complaint`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Complaint` (`complaintID`, `complaintMessage`) VALUES (1, 'Error');
INSERT INTO `mydb`.`Complaint` (`complaintID`, `complaintMessage`) VALUES (2, 'hello');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Contract`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Contract` (`ContractID`, `EmployeeId`, `jobTitle`, `floor`, `workingHours`, `salaryPerHour`, `startDate`, `endDate`, `reasenForTermination`) VALUES (1, 1, 'OWNER', '', 100, 100, '2020-12-12', '2020-12-12', 'NONE');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`DeletedEmployee`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`DeletedEmployee` (`employeeID`, `firstName`, `lastName`, `phoneNumber`, `email`, `adress`, `dateOfBirth`, `bsn`, `userName`, `password`) VALUES (2, 'I\'ll', 'Be back', NULL, NULL, NULL, NULL, 123, 'i', '1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Department`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Department` (`departmentID`, `departmentName`) VALUES (1, 'Sales');
INSERT INTO `mydb`.`Department` (`departmentID`, `departmentName`) VALUES (2, 'Office');
INSERT INTO `mydb`.`Department` (`departmentID`, `departmentName`) VALUES (3, 'Depot');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Employee`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Employee` (`employeeID`, `firstName`, `lastName`, `phoneNumber`, `email`, `adress`, `dateOfBirth`, `bsn`, `userName`, `password`) VALUES (1, 'Lars', 'Kluijtmans', 0000, 'lars@gmail.com', NULL, NULL, 1234, 'Lars', '1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Jobs`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Jobs` (`jobID`, `jobTitle`) VALUES (1, 'Owner');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Product`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Product` (`productID`, `barcode`, `ProductName`, `PorductType`, `AmountInDepot`, `AmountInSales`) VALUES (1, 'k1', 'Knife', 'Kitchen and Home', 100, 12);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`ProductTypes`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`ProductTypes` (`ProductTypeID`, `ProductTypesName`) VALUES (1, 'Kitchen and Home');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Scheduel`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Scheduel` (`empID`, `scheduelDay`, `time`) VALUES (1, 'wednesday', 'morning');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Shifts`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Shifts` (`day`, `Morning`, `Afternoon`, `evening`) VALUES ('monday', 1, 1, 1);
INSERT INTO `mydb`.`Shifts` (`day`, `Morning`, `Afternoon`, `evening`) VALUES ('tuseday', 1, 1, 1);
INSERT INTO `mydb`.`Shifts` (`day`, `Morning`, `Afternoon`, `evening`) VALUES ('wednsday', 1, 1, 1);
INSERT INTO `mydb`.`Shifts` (`day`, `Morning`, `Afternoon`, `evening`) VALUES ('thursday', 1, 1, 1);
INSERT INTO `mydb`.`Shifts` (`day`, `Morning`, `Afternoon`, `evening`) VALUES ('friday', 1, 1, 1);
INSERT INTO `mydb`.`Shifts` (`day`, `Morning`, `Afternoon`, `evening`) VALUES ('stareday', 1, 1, 1);
INSERT INTO `mydb`.`Shifts` (`day`, `Morning`, `Afternoon`, `evening`) VALUES ('sunday', 1, 1, 1);

COMMIT;


ALTER TABLE `dbi461266`.`shelfreplenishment` 
ADD INDEX `ProductID_idx` (`ProductID` ASC):
;
ALTER TABLE `dbi461266`.`shelfreplenishment` 
ADD CONSTRAINT `ProductID`
  FOREIGN KEY (`ProductID`)
  REFERENCES `dbi461266`.`product` (`ProductID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `dbi461266`.`restockreplenishment` 
ADD CONSTRAINT `ProductID2`
  FOREIGN KEY (`ProductID`)
  REFERENCES `dbi461266`.`product` (`ProductID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
